### ISSUE TITLE
The command "greenkeeper-lockfile-update" failed and exited with 127 during .

### ISSUE THREAD

**Issue by srv-twry** [greenkeeperio/greenkeeper#844]
After the recent updates, the command `greenkeeper-lockfile-update` fails. It has started to happen in the past 10-12 hrs. We received request to update the permissions by the greenkeeper bot and after approving the updated permissions, each and every travis build is failing. 

Some more details if needed.

### Travis config
```yaml
{
  "os": "linux",
  "env": "CXX=g++-4.8 JOBS=1 PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1",
  "dist": "trusty",
  "cache": {
    "yarn": true
  },
  "group": "stable",
  "addons": {
    "apt": {
      "sources": [
        "ubuntu-toolchain-r-test"
      ],
      "packages": [
        "g++-4.8"
      ]
    },
    "chrome": "stable"
  },
  "script": [
    "touch .env",
    "node scripts/l10n.js generate",
    "yarn lint:scss",
    "COVERAGE=true yarn test",
    "ROOT_URL=open-event-frontend ember build -prod"
  ],
  "install": "yarn",
  "node_js": "8",
  "language": "node_js",
  "after_script": "greenkeeper-lockfile-upload",
  "after_success": [
    "bash <(curl -s https://codecov.io/bash)",
    "bash kubernetes/travis/docker-deploy.sh"
  ],
  "before_script": "greenkeeper-lockfile-update",
  "before_install": "yarn global add greenkeeper-lockfile@1"
}
```

### Failure log on travis
```
0.10s$ greenkeeper-lockfile-update
greenkeeper-lockfile-update: command not found
The command "greenkeeper-lockfile-update" failed and exited with 127 during .
```
Travis build link: https://travis-ci.org/fossasia/open-event-frontend/jobs/404575615
