### ISSUE TITLE
X is not a greenkeeper branch

### ISSUE THREAD

**Issue by cyberhck** [greenkeeperio/greenkeeper#940]
### This might be a bug, I'm not sure.

Yesterday I setup greenkeeper on one of my private repository, when my build runs, and I run greenkeeper update lock file and later upload lock file, it says <name of branch> is not a greenkeeper branch.

Relevant parts of travis.yml looks something like this:
```yml
language: php

cache:
  directories:
    - .composer/cache
    - node_modules

before_install:
  - docker --version
  - docker-compose --version
  - docker login -u $DOCKERHUB_CI_USER -p $DOCKERHUB_CI_TOKEN
  - npm i -g @crazyfactory/docker-project-cli
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - echo "<?php " > config.local.php
  - npm i -g greenkeeper-lockfile@1

install:
  - dopr pull && dopr up -d
  - dopr npm run start:dev

before_script: greenkeeper-lockfile-update

script:
  - dopr npm run test

after_script:
  - greenkeeper-lockfile-upload
```
Saying X isn't a greenkeeper sounds correct, since greenkeeper simply pushes to one of our branch, but for some reason, there has been no activity from greenkeeper on this repository.
